apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  POSTGRES_DB: postgres
  AWS_BUCKET: mono123456
  AWS_REGION: postgres
  JWT_SECRET: testing
  URL: http://localhost:8100